### ISSUE TITLE
Support per-project configuration

### ISSUE THREAD

**Issue by stevenhauser** [stevenhauser/spec-maker#1]
It'd be nice to use the default settings when no project config exists and override them with project config settings when they do exist. Need to look into how other packages handle per-project settings.

**Comment by jakesankey** [comment]
I'd also love this feature. If you commonly work on a variety of projects, it is uncommon that they all use the same naming conventions, paths, etc.

**Comment by stevenhauser** [comment]
True. I need to update with the new Atom API anyway.

**Comment by stevenhauser** [comment]
@jakesankey I don't know that there's a great way to do this w/o requiring a separate configuration file either in the project (which I think is a bummer) or a "global" settings file for all projects. The [project manager](https://atom.io/packages/project-manager) package appears to already handle this very nicely and makes a lot more sense than doing it in this package IMO.

From what I gather, you can open a project in project manager, save it, which will add it to the global project manager configuration file, and then add `settings` in that file for each of your projects. For instance:

```cson
'spec-maker':
  'title': 'spec-maker'
  'paths': ['path/to/your/project'],
  'settings':
    'spec-maker.houseOfPane': 'right'
    'spec-maker.specSuffix': '-specification'
```

So I'm going to close this issue since I think project manager already fulfills this way better and more thoroughly than could be done in this package alone.
