### ISSUE TITLE
Symlink paths not handled correctly

### ISSUE THREAD

**Issue by jakesankey** [stevenhauser/spec-maker#7]
When you try to use spec maker on a project which is opened via a symlink, spec-maker has some odd behavior.

To reproduce:
1. create a project somewhere on the filesystem
2. create a symlink of that directory in another location
3. open the project form the symlink
4. try using spec-maker

**Comment by stevenhauser** [comment]
@jakesankey do you know if this was just introduced in 0.4.0 or did it exist prior?

**Comment by stevenhauser** [comment]
Also I'm not able to reproduce this using the steps above. When I open the symlink, everything opens "as normal" or whatever, and spec maker creates specs as…ex-spec-ted.

**Comment by jakesankey** [comment]
I don't know when it was introduced. What happens for me in this scenario is I end up with a spec created in a new folder structure of /Users/username/real/path/not/sum/path/projectname/spec/blah-spec.coffee. 

This new Users root dir is put in the root of my project. Quite odd. 

Jake

**Comment by stevenhauser** [comment]
What OS are you on?

**Comment by jakesankey** [comment]
Mac

Jake

**Comment by stevenhauser** [comment]
Weird, same here. And I assume you're on the latest version of Atom? 

Since I can't reproduce this, it makes it extremely difficult for me to debug. If you're up for digging in though, feel free to submit a PR if you determine what the issue is and I'll happily merge it in.
